"""empty message

Revision ID: 9661d522298d
Revises: 3fdd38a93875
Create Date: 2023-06-02 23:30:36.024917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9661d522298d'
down_revision = '3fdd38a93875'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('to_currency', sa.Enum('usd', 'euro', 'yuan', 'yen', 'sgd', name='currencylist'), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('from_crypto', sa.Enum('btc', 'eth', 'usdt', 'doge', 'trc', name='cryptolist'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cryptos_id'), 'cryptos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cryptos_id'), table_name='cryptos')
    op.drop_table('cryptos')
    # ### end Alembic commands ###
